### PR TITLE
Smashing Magazine Project

### PR DESCRIPTION
**Pull request by tadeuasarro**
This project is based in the Smashing Magazine Homepage, presented as requirement of the Microverse fifth project;

Linters have been run;
We have tried to comply the most with the actual web page, but no responsiveness was put to use.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @tadeuasarro and @Prabhakarzx, great job with this project :+1: You have indeed cloned the project :slightly_smiling_face: Our commit messages are descriptive, linter check passed, and validator check successfully. However, to get our project approved, we need to address the comments below: :100: 
- Kindly improve the README, by addressing the following; let us move the contents in the ```Acknowledgements``` to the description. Update the Acknowledgement, all one of the Authors need fixing
- Let us apply the DRY rule to our CSS file. We have repeating properties
- Let us implement the ```Float``` CSS property in this project
ru
- Let us consider the elements background and font colors since this project focuses on HEATMAP
ht

Kindly implement these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Prabhakarzx** [comment]
### Hello @addod19,
**Greetings of the Day!**
We hope you are healthy and safe!
We've just made all of the changes required!
**Thank You for the detailed review!**
Thanks!

**Review by elmejdki — APPROVED** [review]
# status: Approved :smiley: 
# Great job guys :clap: :clap: :clap: your clone is really similar to the original page :tophat:  congratulations :star: 

now you can merge to master your project approved.

## Happy Coding :tophat:

**Comment by Prabhakarzx** [comment]
### Thank you so much @elmejdki for taking your time to review our code!
**We learnt a lot along the way to make bring this project upto this level of similarity!**
### Especially I want to thank @tadeuasarro who is very supportive and collaborative.
**Thank You!**

**Pull request merged**
